ons:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "shruti-test-414408"
      dataset: "test_lbg"
      threads: 1
      timeout_seconds: 300
      priority: interactive